version: "3.8"

volumes:
    postgres_data: {}

services:
    db:
        image: postgres:alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./db/.env
        networks:
            - api_network
        ports:
            - 5432:5432

    api:
        container_name: croneye_api
        build:
            context: ./api
            dockerfile: Dockerfile
        env_file:
            - ./api/project/.env
        volumes:
            - ./api:/app
        networks:
            - api_network
        depends_on:
            - db
        ports:
            - 5001:5000

networks:
    api_network:
        driver: bridge
